export const States: State[] = [
  { id: 0, name: 'Alabama', abbreviation: 'AL' },
  { id: 1, name: 'Alaska', abbreviation: 'AK' },
  { id: 1, name: 'Arizona', abbreviation: 'AZ' },
  { id: 1, name: 'Arkansas', abbreviation: 'AZ' },
  { id: 1, name: 'American Samoa', abbreviation: 'AS' },
  { id: 2, name: 'California', abbreviation: 'CA' },
  { id: 3, name: 'Colorado', abbreviation: 'CO' },
  { id: 4, name: 'Connecticut', abbreviation: 'CT' },
  { id: 6, name: 'Delaware', abbreviation: 'DE' },
  { id: 5, name: 'District of Colombia', abbreviation: 'DC' },
  { id: 7, name: 'Florida', abbreviation: 'FL' },
  { id: 8, name: 'Georgia', abbreviation: 'GA' },
  { id: 8, name: 'Guam', abbreviation: 'GU' },
  { id: 8, name: 'Hawaii', abbreviation: 'HI' },
  { id: 11, name: 'Idaho', abbreviation: 'ID' },
  { id: 10, name: 'Illinois', abbreviation: 'IL'},
  { id: 9, name: 'Indiana', abbreviation: 'IN'},
  { id: 9, name: 'Iowa', abbreviation: 'IA'},
  { id: 12, name: 'Kansas', abbreviation: 'KS'},
  { id: 13, name: 'Kentucky', abbreviation: 'KY' },
  { id: 13, name: 'Louisiana', abbreviation: 'LA' },
  { id: 16, name: 'Maine', abbreviation: 'ME'},
  { id: 15, name: 'Maryland', abbreviation: 'MD' },
  { id: 14, name: 'Massachussets', abbreviation: 'MA' },
  { id: 17, name: 'Michigan', abbreviation: 'MI' },
  { id: 18, name: 'Minnesota', abbreviation: 'MN' },
  { id: 15, name: 'Mississippi', abbreviation: 'MS' },
  { id: 19, name: 'Missouri', abbreviation: 'MO'},
  { id: 20, name: 'Montana', abbreviation: 'MT' },
  { id: 15, name: 'Nebraska', abbreviation: 'NE' },
  { id: 25, name: 'Nevada', abbreviation: 'NV' },
  { id: 22, name: 'New Hampshire', abbreviation: 'NH' },
  { id: 23, name: 'New Jersey', abbreviation: 'NJ' },
  { id: 24, name: 'New Mexico', abbreviation: 'NM' },
  { id: 26, name: 'New York', abbreviation: 'NY'},
  { id: 21, name: 'North Carolina', abbreviation: 'NC' },
  { id: 21, name: 'North Dakota', abbreviation: 'NC' },
  { id: 21, name: 'Northern Mariana Islands', abbreviation: 'MP' },
  { id: 27, name: 'Ohio', abbreviation: 'OH' },
  { id: 27, name: 'Oklahoma', abbreviation: 'OK' },
  { id: 28, name: 'Oregon', abbreviation: 'OR' },
  { id: 29, name: 'Pennsylvania', abbreviation: 'PA' },
  { id: 29, name: 'Peurto Rico', abbreviation: 'PR' },
  { id: 30, name: 'Rhode Island', abbreviation: 'RI' },
  { id: 31, name: 'South Carolina', abbreviation: 'SC'},
  { id: 21, name: 'South Dakota', abbreviation: 'SD' },
  { id: 32, name: 'Tennessee', abbreviation: 'TN' },
  { id: 33, name: 'Texas', abbreviation: 'TX' },
  { id: 34, name: 'Utah', abbreviation: 'UT' },
  { id: 36, name: 'Vermont', abbreviation: 'VT' },
  { id: 35, name: 'Virginia', abbreviation: 'VA' },
  { id: 35, name: 'Virgin Islands', abbreviation: 'VI' },
  { id: 37, name: 'Washington', abbreviation: 'WA' },
  { id: 39, name: 'West Virginia', abbreviation: 'WV'},
  { id: 38, name: 'Wisconson', abbreviation: 'WI'},
  { id: 40, name: 'Wyoming', abbreviation: 'WY'},
]

export interface State {
  id: number;
  name: string;
  abbreviation: string;
  }
